// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EvStorionX.Infrastructure.Persistence;

#nullable disable

namespace EvStorionX.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    partial class MigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Migration.Domain.Entities.Archive", b =>
                {
                    b.Property<string>("ArchiveId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("archive_id");

                    b.Property<bool>("LegalHold")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("legal_hold");

                    b.Property<string>("OwnerUpn")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("owner_upn");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("VaultStore")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("vault_store");

                    b.HasKey("ArchiveId")
                        .HasName("pk_archives");

                    b.ToTable("archives");
                });

            modelBuilder.Entity("Migration.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("ItemId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("item_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload");

                    b.Property<Guid>("RunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("run_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_audit_events_run_id");

                    b.HasIndex("RunId", "EventType")
                        .HasDatabaseName("ix_audit_events_run_id_event_type");

                    b.ToTable("audit_events");
                });

            modelBuilder.Entity("Migration.Domain.Entities.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("item_id");

                    b.Property<string>("ArchiveId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("archive_id");

                    b.Property<string>("Bcc")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("bcc");

                    b.Property<string>("Cc")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("cc");

                    b.Property<string>("ContentPartIds")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("content_part_ids");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("folder_path");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("from");

                    b.Property<string>("MessageClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("message_class");

                    b.Property<string>("RetentionCategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("retention_category");

                    b.Property<DateTime>("SentDateUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_date_utc");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("varchar(998)")
                        .HasColumnName("subject");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("to");

                    b.HasKey("ItemId")
                        .HasName("pk_items");

                    b.HasIndex("ArchiveId")
                        .HasDatabaseName("ix_items_archive_id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Migration.Domain.Entities.MigrationRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ArchiveId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("archive_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("extracted_at_utc");

                    b.Property<DateTime?>("IngestedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ingested_at_utc");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("SourceItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("source_item_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TargetArchive")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("target_archive");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("target_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("pk_migration_records");

                    b.HasIndex("ArchiveId")
                        .HasDatabaseName("ix_migration_records_archive_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_migration_records_idempotency_key");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_migration_records_status");

                    b.ToTable("migration_records");
                });

            modelBuilder.Entity("Migration.Domain.Entities.RunCheckpoint", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("run_id");

                    b.Property<string>("Phase")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("phase");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext")
                        .HasColumnName("metadata");

                    b.HasKey("RunId", "Phase")
                        .HasName("pk_run_checkpoints");

                    b.ToTable("run_checkpoints");
                });

            modelBuilder.Entity("Migration.Domain.Entities.SisPart", b =>
                {
                    b.Property<string>("PartId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("part_id");

                    b.Property<string>("DataRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("data_ref");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("PartId")
                        .HasName("pk_sis_parts");

                    b.ToTable("sis_parts");
                });
#pragma warning restore 612, 618
        }
    }
}
