/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all known migration runs (in-memory, resets on restart). */
        get: operations["ListRuns"];
        put?: never;
        /** Start a new migration run (or resume from checkpoint when RunId matches a prior run). */
        post: operations["StartRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll the status of an in-progress or completed migration run. */
        get: operations["GetRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel the active task for a run and restart it from the last checkpoint. */
        post: operations["ResumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream audit events for a run. Use ?format=csv for CSV download. */
        get: operations["GetAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare local migration records against storionX /stats for discrepancies. */
        get: operations["GetReconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Placeholder: returns discovered EV archives. */
        get: operations["ListArchives"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArchiveResponse: {
            archiveId: string;
            type: components["schemas"]["ArchiveType"];
            ownerUpn: null | string;
            legalHold: boolean;
            vaultStore: string;
        };
        ArchiveSummary: {
            /** Format: int64 */
            migrated: number | string;
            /** Format: int64 */
            alreadyPresent: number | string;
            /** Format: int64 */
            skipped: number | string;
            /** Format: int64 */
            failed: number | string;
        };
        /** @enum {unknown} */
        ArchiveType: "Mailbox" | "Journal" | "Fsa";
        AuditEventResponse: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            timestampUtc: string;
            eventType: string;
            itemId: null | string;
            payload: string;
            /** Format: uuid */
            runId: string;
        };
        ReconciliationReport: {
            /** Format: uuid */
            runId: string;
            /** Format: date-time */
            generatedAtUtc: string;
            missingInTarget: string[];
            mismatchedInTarget: string[];
            unexpectedInTarget: string[];
            isClean: boolean;
        };
        RunCreatedResponse: {
            /** Format: uuid */
            runId: string;
        };
        RunDetailResponse: {
            /** Format: uuid */
            runId: string;
            status: string;
            /** Format: date-time */
            startedAt: string;
            summary: null | components["schemas"]["RunSummary"];
        };
        RunListItemResponse: {
            /** Format: uuid */
            runId: string;
            status: string;
            /** Format: date-time */
            startedAt: string;
        };
        RunSummary: {
            /** Format: uuid */
            runId: string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            finishedAtUtc: null | string;
            /** Format: int32 */
            totalArchives: number | string;
            /** Format: int64 */
            totalItems: number | string;
            /** Format: int64 */
            migrated: number | string;
            /** Format: int64 */
            alreadyPresent: number | string;
            /** Format: int64 */
            orphaned: number | string;
            /** Format: int64 */
            skipped: number | string;
            /** Format: int64 */
            failed: number | string;
            byArchive: {
                [key: string]: components["schemas"]["ArchiveSummary"];
            };
        };
        StartRunRequest: {
            /** Format: uuid */
            runId?: null | string;
            dryRun?: null | boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItemResponse"][];
                };
            };
        };
    };
    StartRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAudit: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
        };
    };
    GetReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationReport"];
                };
            };
        };
    };
    ListArchives: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveResponse"][];
                };
            };
        };
    };
}
